pipeline {
    agent any

    environment {
        AWS_CREDENTIALS = credentials('aws-secret-key')  // Use the correct ID of your AWS credentials stored in Jenkins
        PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin"  // Include the correct path for AWS CLI
    }

    stages {
        stage('Checkout from GitHub') {
            steps {
                git branch: 'integration-jobs', url: 'https://github.com/Manzoor404/integration-jobs.git'
            }
        }

        stage('Upload to S3') {
            steps {
                withAWS(credentials: 'aws-secret-key', region: 'us-east-1') {
                    script {
                        // Upload the Glue ETL script to S3
                        sh """
                        aws s3 cp AWSGlueSpotifyIntegration/glue_spotify_integration.py s3://syedmanzoor/staging_data/Spotify/GlueSpotify/glue_spotify_integration.py
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded and the Glue script was uploaded to S3.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}