pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pull the latest code from GitHub
                git branch: 'integration-jobs', url: 'https://github.com/Manzoor404/integration-jobs.git'
            }
        }

        stage('Trigger Airflow DAG') {
            steps {
                script {
                    // Trigger Airflow DAG that runs the ETL pipeline in DataProc
                    sh """
                    curl -X POST \
                        http://your-airflow-server:8080/api/v1/dags/your_dag_id/dagRuns \
                        -H 'Content-Type: application/json' \
                        -H 'Authorization: Basic your_encoded_auth_token' \
                        -d '{
                              "conf": {
                                "gcs_path": "gs://your-gcs-bucket/path/to/csv",
                                "dataProcCluster": "your-dataproc-cluster"
                              }
                            }'
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}