pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pull the latest code from GitHub
                git branch: 'integration-jobs', url: 'https://github.com/Manzoor404/integration-jobs.git'
            }
        }

        stage('Upload to GCS') {
            steps {
                script {
                    // Upload the ETL script to the GCS bucket
                    sh """
        stage('Check PATH') {
            steps {
                script {
                    // Print the PATH in Jenkins environment
                    sh "echo \$PATH"
                }
            }
        }

        stage('Upload to GCS') {
            steps {
                script {
                    // Add gsutil path before running the command
                    sh """
                    export PATH=/Users/syedmanzoor/google-cloud-sdk/bin:\$PATH
                    gsutil cp dataproc_airflow_integration_powerbi/dataproc_airflow_etl_script.py gs://syedmanzoor-bucket/dataproc_scripts/dataproc_airflow_etl_script.py
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded'
        }
        failure {
            echo 'Pipeline failed'
        }
    }

}

